### ISSUE TITLE
[question] applicability to 1D chromatograms

### ISSUE THREAD

**Issue by Adafede** [soerendip/ms-peakonly#1]
Hi, 
Very nice work!

Since you did a partial re-write of peakonly and get to know it well, I would have the following question:

In your opinion, what would be the easiest way to use peakonly to detect peaks, not in a 2D chromatogram (retention time, intensity, m/z), but in a 1D chromatogram (retention time, intensity) coming from another detector than MS. Peak shapes should be similar.

I would love to hear from you about it. If my question is unclear for you, I am happy to develop and/or share .mzML files with multiple spectra/chromatogram objects coming from various detectors in it! 

Best,

**Comment by sorenwacker** [comment]
It is just a wrapper around the code from the original repository. So, I did not rewrite the code or retrain the models. I think, the nature of how neural networks work, you would have to retrain the networks and change the network architecture in order to make it work for 1D case. Did you try the `find_peaks` function from `scipy.signal`? You may have to add a bit of preprocessing like smoothing to make it work.
